### PR TITLE
add support for global request options

### PR DESCRIPTION
**Pull request by sf-csarov**

### CODE REVIEW

**Comment by sf-csarov** [comment]
Added tests; reverted version bump;

**Comment by vernak2539** [comment]
If you could please fix the alignment to be the same as the current style in the file. (tabs I believe).

This PR --> https://github.com/salesforce-marketingcloud/FuelSDK-Node-Auth/pull/71 <-- should be fixed and merged first as we will update this module to have the new version once complete

**Comment by sf-csarov** [comment]
I found how to "fix" the indenting. Sometimes the code uses 4 spaces for indentation, sometimes the "tab" character. Changed from 4 spaces to tab character and it seems it is fixed.

**Comment by vernak2539** [comment]
Please update to the latest fuel-auth version

**Comment by vernak2539** [comment]
published as `fuel-soap@2.1.0`

**Pull request merged**
