### PR TITLE
Handle reqOptions Parameters in SOAP Calls

### PR DESCRIPTION
**Pull request by brianfeltis**
Added handling for reqOptions parameters passed into retrieve, create, update, and delete methods

### CODE REVIEW

**Comment by vernak2539** [comment]
@brianfeltis please add a test that demonstrates this added functionality. There is a folder with tests already that should give a few examples. Written in Mocha.

This module is in need of an update (in general). I'll hopefully be able to get to it soon

**Comment by brianfeltis** [comment]
@vernak2539 How would you like me to test?  The reqOptions object does not change the response and would, therefore, just be a duplicate test.

**Comment by vernak2539** [comment]
@brianfeltis Okay, so here's what I was thinking. I usually take more of a TDD approach, but no worries. You can test the following.

1. `_addReqOptionsToRequestBody` since it's a new method. just to make sure it does what you want.
2. then where you've added all those `if(reqOptions) {...` I would mock the function from number 1 above, and just make sure it's called in those cases you've added. Sinon, which is included in the dev deps, should give you the ability to do this.

I guess I'm really after getting the first one done. Make sense? If not, let me know and we can go through it more

**Comment by brianfeltis** [comment]
@vernak2539 I modified the original solution to handle all of the different request types.  Also, I added a unit test that tests both the functionality and, conditionally, whether or not it is called.

**Comment by vernak2539** [comment]
@brianfeltis great thanks. I'll get to merging this later today

**Comment by brianfeltis** [comment]
@vernak2539 any update on this?

**Comment by vernak2539** [comment]
@brianfeltis I'm sorry for the delay. I'm trying to get another person to look at it, as I have limited experience with SOAP in general. I understand what you're doing, but not why. 

@aydrian, who wrote this module originally has since left. Without a little feedback from @dougwilson or @aydrian I have trouble determining whether or not it will affect current users of the module.

**Comment by vernak2539** [comment]
@brianfeltis I've chatted with @dougwilson about this change, and unfortunately we can't merge it for a few reasons:

1. It has the potential to overwrite properties in the body if they are in the `reqOptions`
2. It will add unneeded properties to the SOAP objects (invalid objects)
3. We are mixing concerns as `reqOptions` is really for the request module options

It looks like you're needing to add "Options" to 4 of the SOAP Actions (QueryAllAccounts being one of the them), if you let me know what options you want added to each method, I can add them for you. All you would need to do is add something (format to be determined) to the options object in the requests you're making.

Or you can make a PR that does this.

**Comment by brianfeltis** [comment]
@vernak2539 We definitely need QueryAllAccounts fixed, at this point thats the only one I have identified.  Please let me know when this can be done.

**Pull request closed without merging**
