### PR TITLE
Perform Operation and More Examples

### PR DESCRIPTION
**Pull request by angrycider**
Adding Perform Operation and more examples to ReadMe

### CODE REVIEW

**Comment by vernak2539** [comment]
@angrycider this is amazing! thanks so much! I'll be able to merge and publish tomorrow hopefully

**Comment by vernak2539** [comment]
published as `v1.5.0`. Thanks for the PR

**Comment by angrycider** [comment]
No worries...This library has helped me quite a bit, I'm happy to contribute back.

**Comment by angrycider** [comment]
I didn't think to look at issues, but looks like there might be a couple related to perform that you could close out.  I should have some other perform examples to add in the next couple of days...specifically around executing queries and starting programs/automations

**Pull request merged**
