### PR TITLE
Integration of queryAllAccounts

### PR DESCRIPTION
**Pull request by vernak2539**
@brianfeltis this is along the lines of what you need correct?

@dougwilson this is the basics of what we chatted about right?

### CODE REVIEW

**Comment by brianfeltis** [comment]
@vernak2539 This looks like it should take care of my immediate need.

**Comment by vernak2539** [comment]
@brianfeltis this has been published as `v1.3.0`

**Comment by dougwilson** [comment]
Only somewhat. This change is now creating invalid SOAP payloads to our API. Only `Retrieve` and `Query` actions support query all accounts. All the other modified actions in the PR are not valid SOAP payloads.

**Comment by vernak2539** [comment]
Lovely, so basically remove them from `create`, `udpate`, and `delete` @dougwilson?

**Pull request merged**
