### PR TITLE
closes salesforce-marketingcloud/FuelSDK-Node-SOAP#122 Added Schedule…

### PR DESCRIPTION
**Pull request by DougMidgley**
closes salesforce-marketingcloud/FuelSDK-Node-SOAP#122 Added Scheduled method

### CODE REVIEW

**Comment by DougMidgley** [comment]
@manivinesh @sfdrogojan @sfcbetiuc  any chance one of you can help with getting this merged?

**Comment by sfcbetiuc** [comment]
@DougMidgley, PR is being reviewed

**Comment by manivinesh** [comment]
Looks like @sfcbetiuc tried to run the tests with the new changes and noticed 17 tests are failing which were not failing in the master branch. 

Issue: 
Before the PR, the tests were asserting based on the length of object and it was expecting it to be 1 always, now that the new changes make the filters to actually work, the length is now coming as more than 1 and it cause those tests to fail.

To fix this issue:
1. Pull in the latest code from the master branch and 
2. Fix the length issue in the failing tests.

@sfcbetiuc @DougMidgley

**Comment by DougMidgley** [comment]
Hi @manivinesh  @sfcbetiuc  thanks for picking this up.
I ran tests locally based on this version and no test failures were caught. I also see the last build https://travis-ci.org/salesforce-marketingcloud/FuelSDK-Node-SOAP/builds/586619208?utm_source=github_status&utm_medium=notification did not show any errors so would be good to understand what can be done here...

**Comment by manivinesh** [comment]
@DougMidgley Apologies, i meant to add that comment on the FuelSDK-Node module.

**Comment by DougMidgley** [comment]
Hi @manivinesh  :) cool, so this can be merged?

**Comment by manivinesh** [comment]
@DougMidgley Yes, @sfcbetiuc will merge and release the package soon.

**Comment by sfcbetiuc** [comment]
@DougMidgley, can you please increase the version to 2.2.4 in package.json?

**Pull request merged**
